### ISSUE TITLE
I have some files missing?

### ISSUE THREAD

**Issue by shirish47** [dimhoff/si4010prog#1]
si4010_rom_keil.a51
Si4010_link.c, etc... 
where should I get this from ? :(

**Comment by dimhoff** [comment]
Where would you need them for? There doesn't seem to be anything in the 
si4010prog repo that references them. Neither does the project use Keil.

Please explain what you are trying to do.

Kind regards,

David

**Comment by shirish47** [comment]
I am trying to figure out how can I code in silicon lab Si4010.. may be I am lost :( I downloaded Si4010 key_fob demo from some link. bt it had some missing libs. anyways How can I program with Si lab and flash it to the chip? I think ur source helps in just flashing is it?

**Comment by shirish47** [comment]
sorry dear my mistake. :)

**Comment by dimhoff** [comment]
yes, only for flashing under Linux without the official programmer. For 
support about the Silabs software please ask to Silabs: 
http://www.silabs.com.

David
