### ISSUE TITLE
Help with FX2

### ISSUE THREAD

**Issue by markusdd** [dimhoff/si4010prog#2]
Hi,

I have an FX2 mini board here and I can get the tool to connect after building the driver, but I am lost as to how to connect it physically.
The README uses pin designators I do not have. I have PA0-x PB0-x PD0x, some CTL pins, an SDA and SCL etc.

I tried using the oscilloscope but cannot find anything.

This is my board 
![Lcsoft-miniboard-front](https://github.com/dimhoff/si4010prog/assets/25175069/79c4a6ab-1bd3-469e-872d-c9a514d1d8d7)

(I have pulled J1 so it comes upo as the generic Cypress EZ-USB that the driver expects)

When I use it I always get back 0x00 for both Device and Revision ID from `s4010prog identify `

**Comment by dimhoff** [comment]
Hi, 

First of all did you black list the usbtest module? If you run `lsmod` and see the usbtest module you need to unload it and blacklist it

    echo 'blacklist usbtest' | sudo tee /etc/modprobe.d/si4010prog.conf

I used the pin names of the SI4010 chip. But the pin naming on the board is quit logical: PA1 == IOA.1; PA2 == IOA.2.
Here is how I connected a RFM60S module:

![20231119_140830](https://github.com/dimhoff/si4010prog/assets/7550562/f5ea9356-9d09-4e8a-851d-ff85c05628ca)

Finally you should load the c2_fx2 firmware into the FX2 device. This can be done using cycfx2prog:

    sudo cycfx2prog prg:c2prog.ihx run

Now when you run si4010prog identify:

    $ sudo ./si4010prog identify
    Device ID: 0x24; Revision ID: 0x02

**Comment by markusdd** [comment]
Thanks for your quick response!

usbtest is not present on the Fedora I am using, I checked for that following your README

I guess the issue I am having is that I missed that I need to load the fx2 firmware by myself, I thought this gets pushed as a driver once the device is being enumerated by si4010prog, so that will be my problem.

I will try this and get back to you shortly, thanks so much for the help!

**Comment by markusdd** [comment]
ok next question right away: how do I generate this firmware ihx file?

I ran your normal cmake build and si4010prog is running fine, but I do not find this firmware.

**Comment by markusdd** [comment]
ok, I just figured out the driver is built using it's own makefile, and newer distributions package sdcc differently and the generic executable is now called sdcc-sdcc, so I needed to hack the makefile.

I now have ID reading working. And flashing as well!

Thanks so much for this amazing little toolkit, in case you need a Tesla Chargedoor opener hit me up ;)

![F_TuQ3jXMAAewnr](https://github.com/dimhoff/si4010prog/assets/25175069/8ee11193-b282-47ce-b034-ab18de083186)
![F_TuRL6W0AAlqjk](https://github.com/dimhoff/si4010prog/assets/25175069/c208ee90-5ddd-4cd9-aa3a-0e5874bd6695)

**Comment by dimhoff** [comment]
Good to hear it works:)
